Repository piyushpaliwal/nextjs-ambit, pull requests merged in 2023-05, with the labels that each got.

#63 Create Blog “the-ultimate-guide-to-interior-design-bookkeeping”
  pages/article/[slug].tsx
  pages/blogs.tsx
  public/admin/config.yml
  public/img/articles/project-cover-image-3.jpg.jpg
  src/data/articles/myths-with-offshore-outsourcing.md
  src/data/articles/the-ultimate-guide-to-interior-design-bookkeeping.md
Labels: netlify-cms/draft

#66 Create Blog “everything-you-need-to-know-about-federal-taxes”
  public/img/articles/child-tax-credit.jpg
  public/img/articles/child-tax-credit.svg
  public/img/articles/deductible-retirement-.svg
  public/img/articles/deductible-retirement-contributions.jpg
  public/img/articles/earned-income-tax-credit.png
  public/img/articles/federal-tax-return-tax-preparation.png
  public/img/articles/federal-tax-return.svg
  public/img/articles/household-taxpayers.svg
  public/img/articles/married-taxpayers.svg
  public/img/articles/single-taxpayers.svg
  public/img/articles/tax-benefits.svg
  public/img/articles/tax-brackets.svg
  public/img/articles/us-tax-brackets-2022.jpg
  src/data/articles/everything-you-need-to-know-about-federal-taxes.md
Labels: netlify-cms/pending_publish

#67 Update Blog “everything-you-need-to-know-about-federal-taxes”
  src/data/articles/everything-you-need-to-know-about-federal-taxes.md
Labels: netlify-cms/pending_publish

#69 Create Blog “the-importance-of-us-accounting-standards-for-businesses”
  public/img/articles/us-accounting-standards-for-businesses.png
  public/img/articles/us-accounting-standards-for-businesses.webp
  src/data/articles/the-importance-of-us-accounting-standards-for-businesses.md
Labels: netlify-cms/pending_review

#68 Create Blog “how-to-choose-the-right-online-bookkeeping-service-for-your-business”
  public/img/articles/online-bookkeeping-services.png
  src/data/articles/how-to-choose-the-right-online-bookkeeping-service-for-your-business.md
Labels: netlify-cms/pending_review
